apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: open5gs-upf2
  namespace: open5gs
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: open5gs-upf2
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Pods
        value: 1
        periodSeconds: 30
    scaleDown:
      stabilizationWindowSeconds: 60
      policies:
      - type: Pods
        value: 1
        periodSeconds: 60
