apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: open5gs-upf1-fallback
  namespace: monitoring
  labels:
    release: kps
spec:
  honorLabels: true
  scrapeInterval: 5s
  fallbackScrapeProtocol: PrometheusText0.0.4
  kubernetesSDConfigs:
    - role: Endpoints
      namespaces:
        names: ["open5gs"]
  relabelings:
    - action: keep
      sourceLabels: [__meta_kubernetes_service_name]
      regex: open5gs-upf1-metrics
    - action: keep
      sourceLabels: [__meta_kubernetes_endpoint_port_name]
      regex: metrics
    - action: replace
      targetLabel: __metrics_path__
      replacement: /metrics
    - action: replace
      sourceLabels: [__meta_kubernetes_namespace]
      targetLabel: namespace
    - action: replace
      sourceLabels: [__meta_kubernetes_pod_name]
      targetLabel: pod
    - action: replace
      sourceLabels: [__meta_kubernetes_service_name]
      targetLabel: service
