apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: open5gs-upf1-pps
  namespace: open5gs
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: open5gs-upf1
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: External
      external:
        metric:
          name: upf1_n3_in_pps
        target:
          type: Value
          value: "1500"
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      selectPolicy: Max
      policies:
        - type: Pods
          value: 1
          periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 60
      selectPolicy: Max
      policies:
        - type: Pods
          value: 1
          periodSeconds: 15
